# Generated by Django 4.2 on 2024-12-23 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='SLUG')),
                ('publish_status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', max_length=10, verbose_name='Статус публикации')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('fixed', models.BooleanField(default=False, verbose_name='Зафиксировано')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='title_author_add', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_main_page', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Шапка главной страницы',
                'verbose_name_plural': 'Шапки главной страницы',
                'db_table': 'app_title_main_page',
                'ordering': ['-fixed', '-time_create'],
            },
        ),
        migrations.CreateModel(
            name='TaskMPAsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загловок')),
                ('slug', models.SlugField(max_length=255, verbose_name='SLUG')),
                ('publish_status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', max_length=10, verbose_name='Статус публикации')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('fixed', models.BooleanField(default=False, verbose_name='Зафиксировано')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='task_mp_author_add', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_task_main_page', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Задача главной страницы',
                'verbose_name_plural': 'Задачи главной страницы',
                'db_table': 'app_task_mp_asu',
                'ordering': ['-fixed', '-time_create'],
            },
        ),
        migrations.AddIndex(
            model_name='titlemainpage',
            index=models.Index(fields=['fixed', 'time_create', 'publish_status'], name='app_title_m_fixed_750cae_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmpasu',
            index=models.Index(fields=['fixed', 'time_create', 'publish_status'], name='app_task_mp_fixed_ef4fc0_idx'),
        ),
    ]
