# Generated by Django 4.2 on 2024-12-23 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('publish_status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', max_length=10, verbose_name='Статус публикации')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('fixed', models.BooleanField(default=False, verbose_name='Зафиксировано')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='authro_dep_add', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='arm.department', verbose_name='Родительское подразделение')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_dep', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Подразделение/Отдел/Отделение',
                'verbose_name_plural': 'Подразделения/Отделы/Отделения',
                'db_table': 'app_dep',
            },
        ),
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_arm', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='АРМ')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('ip_addr', models.TextField(max_length=300, verbose_name='IP-адрес/а')),
                ('publish_status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', max_length=10, verbose_name='Статус публикации')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('fixed', models.BooleanField(default=False, verbose_name='Зафиксировано')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='authro_arm_add', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arm_dep', to='arm.department', verbose_name='Подразделение/Отделение/Отдел')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_arm', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'АРМ',
                'verbose_name_plural': 'АРМы',
                'db_table': 'app_arm',
                'ordering': ['-fixed', '-time_create'],
            },
        ),
        migrations.AddIndex(
            model_name='arm',
            index=models.Index(fields=['-fixed', '-time_create', 'publish_status'], name='app_arm_fixed_445905_idx'),
        ),
    ]
