# Generated by Django 4.2 on 2025-01-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arm',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', max_length=10, verbose_name='Статус'),
        ),
    ]
