# Generated by Django 4.2 on 2025-01-13 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_num', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Номер заявки')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('status_task', models.CharField(choices=[('active', 'Актина'), ('in progress', 'В процессе'), ('completed', 'Выполнена')], default='active', verbose_name='Статус заявки')),
                ('publish_status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', verbose_name='Статус публикации')),
                ('fixed', models.BooleanField(default=False, verbose_name='Зафиксировано')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author_task_add', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_dep', to='arm.department', verbose_name='Подразделение/Отдел/Отделение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'app_task_asu',
                'ordering': ['-fixed', '-time_create'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-fixed', '-time_create', 'publish_status'], name='app_task_as_fixed_59bbd6_idx'),
        ),
    ]
